FROM mcr.microsoft.com/mssql/server:2022-latest

# Install mssql-tools (sqlcmd) for restore/backup convenience
USER root
RUN apt-get update && apt-get install -y curl apt-transport-https gnupg \
 && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
 && curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
 && apt-get update \
 && ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev \
 && ln -s /opt/mssql-tools18/bin/sqlcmd /usr/bin/sqlcmd \
 && rm -rf /var/lib/apt/lists/*
USER mssql
